sudo: required

language: dart

services:
  - docker

dart:
  - stable

before_install:
  - sudo service docker restart ; sleep 10
  - docker build -t kafka-cluster kafka-cluster/
  - docker run -d --name kafka-cluster -p 2181:2181 -p 9092:9092 -p 9093:9093 --env ADVERTISED_HOST=127.0.0.1 kafka-cluster
  - docker ps -a
  - sleep 10
  - docker exec kafka-cluster bash -c '$KAFKA_HOME/bin/kafka-topics.sh --create --zookeeper=localhost:2181 --topic dartKafkaTest --partitions 3 --replication-factor 2'
  - docker exec kafka-cluster bash -c '$KAFKA_HOME/bin/kafka-topics.sh --list --zookeeper=localhost:2181'

script:
  - pub run test -r expanded test/all.dart
  - pub run dart_coveralls report -T --retry 2 --debug test/client_test.dart
