sudo: required

language: dart

services:
  - docker

dart:
  - stable

before_install:
  - docker pull spotify/kafka
  - docker run -d -p 2181:2181 -p 9092:9092 spotify/kafka
  - docker ps -a

script:
  - pub run test
