name: 'kafka'
version: 1.0.0-dev
description: Kafka Client for Dartlang
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  semver: "^0.2.1"
  logging: "^0.11.1+1"

dev_dependencies:
  test: "^0.12.4+7"
