name: 'kafka'
version: 0.1.0
description: Kafka client library for Dartlang
homepage: https://github.com/dart-drivers/kafka
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=1.22.0 <2.0.0'

dependencies:
  async: 
  quiver: '>=0.24.0<0.25.0'
  logging: "^0.11.1+1"

dev_dependencies:
  test: "^0.12.4+7"
  mockito: "^0.11.0"
  dart_coveralls: "^0.4.0"
  string_scanner: "^1.0.0"
  source_span: "^1.2.4"
