name: 'kafka'
version: 1.0.0-dev
description: Kafka Client for Dartlang
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  crc32: "^0.1.6"

dev_dependencies:
  test: "^0.12.4+7"
