name: 'kafka'
version: 1.0.0-dev
description: Kafka Client library for Dartlang
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  logging: "^0.11.1+1"

dev_dependencies:
  test: "^0.12.4+7"
  mockito: "^0.11.0"
  dart_coveralls: "^0.4.0"
